# Generated by Django 4.1.5 on 2023-01-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):


    operations = [
        migrations.RenameField(
            model_name='login_regist',
            old_name='contraseña',
            new_name='clave',
        ),
        migrations.RenameField(
            model_name='login_regist',
            old_name='contraseña2',
            new_name='clave2',
        ),
        migrations.AlterField(
            model_name='login_regist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
