# Generated by Django 4.1.5 on 2023-01-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iniciar_sesion', '0004_rename_contraseña_login_regist_clave_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_elec', models.EmailField(max_length=100)),
                ('clave3', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
